version: "3.7"
services:
  frontend:
      container_name: frontend
      build:
        context: ./frontend/
        dockerfile: ./Dockerfile
      hostname: wallet.localhost
      # volumes:
      #   - ./frontend/:/home/node/app
      ports:
        - "80:3000" 
      networks:
        - project_network
  # backend:
  #     container_name: backend
  #     build:
  #       context: ./backend/
  #       dockerfile: ./Dockerfile
  #     hostname: api-wallet.localhost
  #     volumes:
  #       - ./backend:/home/node/app/
  #     ports:
  #       - "3000:3000" 
  #     networks:
  #       - project_network

  # nginx:
  #   container_name: blockchain_nginx
  #   image: nginx:alpine
  #   hostname: project.localhost
  #   tty: true
  #   ports:
  #     - "81:80"
  #   volumes:
  #     - ./docker/nginx:/etc/nginx/conf.d/
  #   depends_on:
  #     - nodejs
  #   networks:
  #     - project_network
      
networks:
  project_network:
    driver : bridge 
